# Generated by Django 3.2.5 on 2021-07-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('F', 'Fixa'), ('V', 'Variável'), ('C', 'Cripto')], default='F', max_length=1)),
                ('valor_unitario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('saldo_carteira', models.FloatField(default=0.0)),
                ('saldo_investido', models.FloatField(default=0.0)),
                ('total_carteira', models.FloatField(default=0.0)),
            ],
        ),
    ]
