# Generated by Django 3.2.5 on 2021-07-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0003_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=True,
        ),
    ]
