# Generated by Django 3.2.5 on 2021-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0006_remove_ativo_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
