# Generated by Django 3.2.5 on 2021-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0007_ativo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
