# Generated by Django 3.2.5 on 2021-07-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0008_alter_ativo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('A', 'Aplicação'), ('R', 'Resgate')], default='A', max_length=1)),
                ('quantidade', models.FloatField(default=0.0)),
                ('total_ativo', models.FloatField()),
                ('taxa_adm', models.FloatField(default=4.9)),
                ('taxa_custodia', models.FloatField(default=8.9)),
                ('total_aplicacao', models.FloatField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora.ativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretora.cliente')),
            ],
        ),
    ]
