# Generated by Django 3.2.5 on 2021-07-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0009_movimentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='valor_unitario',
            field=models.FloatField(default=0.0),
        ),
    ]
