# Generated by Django 3.2.5 on 2021-07-21 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0014_movimentacao_data_aplicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_carteira',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='saldo_investido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='total_carteira',
        ),
    ]
