# Generated by Django 3.2.5 on 2021-07-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0016_auto_20210721_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='client_ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='ativo',
            name='tipo',
            field=models.CharField(choices=[('F', 'Fixa'), ('V', 'Variável'), ('C', 'Cripto')], max_length=1),
        ),
    ]
