# Generated by Django 3.2.5 on 2021-07-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0017_auto_20210721_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='client_ip',
            new_name='cliente_ip',
        ),
    ]
