# Generated by Django 3.2.5 on 2021-07-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0018_rename_client_ip_movimentacao_cliente_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_adm',
            field=models.FloatField(default=5.9),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_custodia',
            field=models.FloatField(default=7.9),
            preserve_default=True,
        ),
    ]
