# Generated by Django 3.2.5 on 2021-07-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0021_alter_movimentacao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.FloatField(default=0.0),
        ),
    ]
