# Generated by Django 3.2.5 on 2021-07-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0026_movimentacao_total_investido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_adm',
            field=models.FloatField(default=5.9),
        ),
    ]
