# Generated by Django 3.2.5 on 2021-07-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0027_alter_movimentacao_taxa_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_adm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_custodia',
            field=models.FloatField(),
        ),
    ]
