# Generated by Django 3.2.5 on 2021-07-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0034_alter_movimentacao_cliente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
