# Generated by Django 3.2.5 on 2021-07-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0036_alter_movimentacao_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='cliente',
            field=models.IntegerField(),
        ),
    ]
