# Generated by Django 3.2.5 on 2021-07-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0042_auto_20210722_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_adm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_custodia',
            field=models.FloatField(),
        ),
    ]
