# Generated by Django 3.2.5 on 2021-07-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0043_auto_20210722_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='valor_unitario',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
