# Generated by Django 3.2.5 on 2021-07-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0044_alter_ativo_valor_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='valor_unitario',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
