# Generated by Django 3.2.5 on 2021-07-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0046_rename_valor_unitario_ativo_preco_mercado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='tipo',
            new_name='tipo_aplicacao',
        ),
    ]
