# Generated by Django 3.2.5 on 2021-07-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0047_rename_tipo_movimentacao_tipo_aplicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='tipo_aplicacao',
            new_name='tipo_transacao',
        ),
    ]
