# Generated by Django 3.2.5 on 2021-07-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0049_movimentacao_tipo_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo_ativo',
            field=models.CharField(max_length=1),
        ),
    ]
