# Generated by Django 3.2.5 on 2021-07-23 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0050_alter_movimentacao_tipo_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ativo',
            name='codigo',
        ),
    ]
