# Generated by Django 3.2.5 on 2021-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretora', '0051_remove_ativo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_adm',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='taxa_custodia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='total_aplicacao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='total_investido',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
